GET http://localhost:8080/users/
Content-Type: application/json

###
GET http://localhost:8080/users/1
Content-Type: application/json

###
POST http://localhost:8080/users/
Content-Type: application/json

{
  "username": "fiqrkm33",
  "email": "fiqrilm33@gmail.com",
  "password": "asdfasdf"
}

###
PUT  http://localhost:8080/users/update
Content-Type: application/json

{
  "id": 1,
  "username": "fiqrkm22",
  "email": "fiqrilm22@gmail.com"
}

###
DELETE http://localhost:8080/users/delete/2
